# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 10:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom2k17', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.TextField(max_length=254)),
                ('address', models.TextField(max_length=2000)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('institute', models.TextField(max_length=1000)),
                ('event', models.TextField(max_length=2000)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
    ]
