# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom2k17', '0003_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='momid',
            field=models.TextField(default='MOM2K17-000', max_length=15),
        ),
        migrations.AddField(
            model_name='school',
            name='momid',
            field=models.TextField(default='MOM2K17sc-000', max_length=15),
        ),
    ]
