# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 18:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom2k17', '0004_auto_20161207_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.TextField(default='pranay', max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='pranay@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='event',
            field=models.TextField(default='pranay', max_length=2000),
        ),
        migrations.AlterField(
            model_name='register',
            name='institute',
            field=models.TextField(default='pranay', max_length=1000),
        ),
        migrations.AlterField(
            model_name='register',
            name='message',
            field=models.TextField(default='pranay', max_length=2000),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.TextField(default='pranay', max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone_number',
            field=models.CharField(default='8305185569', max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
