# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mom2k17', '0005_auto_20161207_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.TextField(default='pranay', max_length=2000),
        ),
        migrations.AlterField(
            model_name='register',
            name='event',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('TME', 'Technical Model Exhibition'), ('IIP', 'Brainwave'), ('QUIZ', 'Quiz'), ('APP', 'Apps Corner'), ('Flash', 'Flash')], max_length=10),
        ),
    ]
