# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 22:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom2k17', '0006_auto_20161208_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='institute',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
