# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom2k17', '0007_auto_20161208_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='momid',
            field=models.CharField(default='MOM2K17-000', max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
