# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom2k17', '0013_auto_20161210_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='message',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
