# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 18:13
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mom2k17', '0014_auto_20161210_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='event',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('TME', 'Technical Model Exhibition'), ('IIP', 'Brainwave'), ('QUIZ', 'Quiz'), ('APP', 'Apps Corner'), ('Flash', 'Flash'), ('OSD', 'Creations')], max_length=100),
        ),
    ]
