# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom2k17', '0015_auto_20161214_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='institute',
            field=models.CharField(max_length=1000),
        ),
    ]
